name: Self hosted greeting

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - name: Test Run
      run: |
        hostname
        echo "Test ${{ secrets.my_secret }}"
