name: Self hosted greeting

on: [push, workflow_dispatch]

jobs:
  greeting:
    runs-on: self-hosted
    env:
      MY_SECRET: ${{ secrets.my_secret }}
    steps:
      - uses: actions/download-artifacts@v3
          name: download website
          path: web.tgz
      - name: Test Run
        run: |
          hostname
          echo "Test variable : ${{ vars.TEST_VARIABLE }}"
      - name: extract website and run
        run: |
          ls
          tar -xvzf web.tgz
          open test.html
